// <auto-generated>
// Rewired Constants
// This list was generated on 19/2/2019 9:44:23 p. m.
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Horizontal")]
        public const int MOVE_HORIZONTAL = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump Flap")]
        public const int JUMP = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Sound")]
        public const int SOUND = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Terrify")]
        public const int TERRIFY = 3;
    }
    public static partial class Category {
        public const int DEFAULT = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int DEFAULT = 0;
        }
        public static partial class Keyboard {
            public const int DEFAULT = 0;
        }
        public static partial class Mouse {
            public const int DEFAULT = 0;
        }
        public static partial class CustomController {
            public const int DEFAULT = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int SYSTEM = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int PLAYER0 = 0;
    }
}
